export const COHORT_ACTIONS = {
    FETCH_STATE_LEVEL_ORG : 'FETCH_STATE_LEVEL_ORG',
    FETCH_COHORTS : 'FETCH_COHORTS',
    TRAINER_COHORTS: 'TRAINER_COHORTS',
    STATE_AND_STATE_ORG: 'STATE_AND_STATE_ORG',
    FILTER_STATE: 'FILTER_STATE',
    FETCH_REQUIREMENTS : 'FETCH_REQUIREMENTS',
    SET_REQUIREMENTS : 'SET_REQUIREMENTS'
}