export const COHORT_ACTIONS = {
<<<<<<< HEAD
    FETCH_STATES: 'FETCH_STATES',
    FETCH_SLOS: 'FETCH_SLOS', 
    FETCH_COHORTS: 'FETCH_COHORTS',
=======
    FETCH_STATE_LEVEL_ORG : 'FETCH_STATE_LEVEL_ORG',
    FETCH_COHORTS : 'FETCH_COHORTS',
    TRAINER_COHORTS: 'TRAINER_COHORTS',
    STATE_AND_STATE_ORG: 'STATE_AND_STATE_ORG',
    FILTER_STATE: 'FILTER_STATE'

>>>>>>> master
}