export const LOCAL_TRAINERS_ACTIONS = {
    UNSET_LOCAL_TRAINERS : 'UNSET_LOCAL_TRAINERS',
    FETCH_LOCAL_TRAINERS : 'FETCH_LOCAL_TRAINERS',
    SET_LOCAL_TRAINERS : 'SET_LOCAL_TRAINERS',
    ADD_LT: 'ADD_LT',
    FETCH_TRAINER_REQUIREMENT_SINGLE : 'FETCH_TRAINER_REQUIREMENT_SINGLE',
    SET_TRAINER_REQUIREMENT_SINGLE : 'SET_TRAINER_REQUIREMENT_SINGLE',
    MARK_COMPLETE :'MARK_COMPLETE',
    UNSET_TRAINER_REQUIREMENT_SINGLE : 'UNSET_TRAINER_REQUIREMENT_SINGLE',
    SCHEDULE_FOR_REQUIREMENT : 'SCHEDULE_FOR_REQUIREMENT',
    UNSET_CONFRIM_SCHEDULE_CREATED : 'UNSET_CONFRIM_SCHEDULE_CREATED',
    SET_CONFIRM_SCHEDULE_CREATED : 'SET_CONFIRM_SCHEDULE_CREATED',
    UNSET_CONFIRM_COMPLETION : 'UNSET_CONFIRM_TASK_SCHEDULED',
    SET_CONFIRM_COMPLETION : 'SET_CONFIRM_COMPLETION'
}


