export const LOCAL_TRAINERS_ACTIONS = {
    UNSET_LOCAL_TRAINERS : 'UNSET_LOCAL_TRAINERS',
    FETCH_LOCAL_TRAINERS : 'FETCH_LOCAL_TRAINERS',
    SET_LOCAL_TRAINERS : 'SET_LOCAL_TRAINERS',
    ADD_LT: 'ADD_LT',
    SHOW_RECENT_ADD: 'SHOW_RECENT_ADD',

    FETCH_TRAINER_REQUIREMENT_SINGLE : 'FETCH_TRAINER_REQUIREMENT_SINGLE',
    SET_TRAINER_REQUIREMENT_SINGLE : 'SET_TRAINER_REQUIREMENT_SINGLE',
    MARK_COMPLETE :'MARK_COMPLETE',
    UNSET_TRAINER_REQUIREMENT_SINGLE : 'UNSET_TRAINER_REQUIREMENT_SINGLE',
    SCHEDULE_FOR_REQUIREMENT : 'SCHEDULE_FOR_REQUIREMENT',

    EXPORT_LOCAL_TRAINERS: 'EXPORT_LOCAL_TRAINERS'

}


