export const LOCAL_TRAINERS_ACTIONS = {
    FETCH_LOCAL_TRAINERS : 'FETCH_LOCAL_TRAINERS',
    SET_LOCAL_TRAINERS : 'SET_LOCAL_TRAINERS',

    ADD_LT: 'ADD_LT',
    EDIT_LOCAL_TRAINER: 'EDIT_LOCAL_TRAINER',

    FETCH_LOCAL_TRAINER_DETAILS: 'FETCH_LOCAL_TRAINER_DETAILS',
    SET_LOCAL_TRAINER_DETAILS: 'SET_LOCAL_TRAINER_DETAILS',

    FETCH_TRAINER_REQUIREMENT_SINGLE : 'FETCH_TRAINER_REQUIREMENT_SINGLE',
    SET_TRAINER_REQUIREMENT_SINGLE : 'SET_TRAINER_REQUIREMENT_SINGLE'

}


