export const NATIONAL_TRAINER_ACTIONS = {
    FETCH_ALL_NATIONAL_TRAINERS : 'FETCH_ALL_NATIONAL_TRAINERS',
    SET_ALL_NATIONAL_TRAINERS : 'SET_ALL_NATIONAL_TRAINERS',
    UNSET_NATIONAL_TRAINERS : 'UNSET_NATIONAL_TRAINERS',
    ADD_NATIONAL_TRAINER : 'ADD_NATIONAL_TRAINER',
    CHANGE_STATUS : 'CHANGE_STATUS',
    FETCH_ONE_NATIONAL_TRAINER : 'FETCH_ONE_NATIONAL_TRAINER',
    SET_ONE_NATIONAL_TRAINER : 'SET_ONE_NATIONAL_TRAINER',
    UPDATE_NATIONAL_TRAINER : 'UPDATE_NATIONAL_TRAINER', 
    CONFIRM_EMAIL : 'CONFIRM_EMAIL',
    UNSET_EMAIL : 'UNSET_EMAIL',
    SET_EMAIL : 'SET_EMAIL',
    REQUEST_PASSWORD_RESET : 'REQUEST_PASSWORD_RESET',
    RESET_PASSWORD : 'RESET_PASSWORD',
    UNSET_COFIRM_PASSWORD_RESET : 'UNSET_COFIRM_PASSWORD_RESET',
    CONFIRM_PASSWORD_RESET : 'CONFIRM_PASSWORD_RESET'
}