export const NATIONAL_TRAINER_ACTIONS = {
    FETCH_ALL_NATIONAL_TRAINERS : 'FETCH_ALL_NATIONAL_TRAINERS',
    SET_ALL_NATIONAL_TRAINERS : 'SET_ALL_NATIONAL_TRAINERS',
    UNSET_NATIONAL_TRAINERS : 'UNSET_NATIONAL_TRAINERS',
    ADD_NATIONAL_TRAINER : 'ADD_NATIONAL_TRAINER',
    CHANGE_STATUS : 'CHANGE_STATUS'
}