export const STATE_LEAD_ACTIONS = {
    FETCH_STATE_LEAD : 'FETCH_STATE_LEAD',
    STATE_LEAD: 'STATE_LEAD',
    FILTER_STATE_LEAD: 'FILTER_STATE_LEAD',
    FETCH_STATE_LEAD_DROPDOWN: 'FETCH_STATE_LEAD_DROPDOWN'
}